import type { Message, Run, Thread } from './domain'

export const threads: Thread[] = [
  {
    id: 'thread-brief',
    title: 'M1 interface pass',
    project: 'Loomi',
    mode: 'work',
    updatedAt: '2m',
    lifecycleStatus: 'active',
    runStatus: 'running',
  },
  {
    id: 'thread-docs',
    title: 'Roadmap alignment',
    project: 'Planning',
    mode: 'work',
    updatedAt: '18m',
    lifecycleStatus: 'active',
    runStatus: 'completed',
  },
  {
    id: 'thread-agent',
    title: 'Agent profile sketch',
    project: 'Lab',
    mode: 'chat',
    updatedAt: '1h',
    lifecycleStatus: 'active',
    runStatus: 'stopped',
  },
]

export const messages: Message[] = [
  {
    id: 'msg-1',
    threadId: 'thread-brief',
    role: 'user',
    content: 'Create a polished M1 shell for Loomi. Keep it desktop-like, compact, and glassy.',
    createdAt: '10:24',
  },
  {
    id: 'msg-2',
    threadId: 'thread-brief',
    role: 'assistant',
    content: 'Set the shell as a three-panel workspace: navigation, cowork canvas, and run rail. Use mock events only.',
    createdAt: '10:25',
    toolCalls: [
      {
        id: 'tool-1',
        name: 'scan_reference',
        status: 'completed',
        summary: 'Mapped Arkloop work mode, timeline, right panel, and artifacts.',
        input: 'Arkloop web workspace files',
        output: 'Work mode, timeline, context compact bar, right panel tabs',
      },
    ],
  },
  {
    id: 'msg-3',
    threadId: 'thread-docs',
    role: 'user',
    content: 'Keep M1 clean. No backend, no auth, no Electron.',
    createdAt: '09:48',
  },
  {
    id: 'msg-4',
    threadId: 'thread-docs',
    role: 'assistant',
    content: 'M1 stays browser-only with a replaceable API boundary and local mock data.',
    createdAt: '09:49',
  },
  {
    id: 'msg-5',
    threadId: 'thread-agent',
    role: 'user',
    content: 'Sketch a small agent profile surface.',
    createdAt: 'Yesterday',
  },
  {
    id: 'msg-6',
    threadId: 'thread-agent',
    role: 'assistant',
    content: 'Use a compact profile card later. For M1, show agent metadata in the right rail only.',
    createdAt: 'Yesterday',
  },
]

export const runs: Run[] = [
  {
    id: 'run-1',
    threadId: 'thread-brief',
    status: 'blocked_on_tool_approval',
    model: 'Claude Sonnet',
    context: '42k / 128k',
    toolCalls: [
      {
        id: 'tc_read_2',
        toolCallId: 'tc_read_2',
        name: 'workspace.read',
        status: 'approval_required',
        approvalStatus: 'required',
        executionStatus: 'blocked',
        summary: 'Read a project file after confirmation',
        input: 'path: web/src/App.tsx',
        output: '',
        argumentsSummary: { path: 'web/src/App.tsx' },
        resultSummary: null,
        errorCode: null,
        errorMessage: null,
      },
    ],
    events: [
      {
        id: 'evt-1',
        type: 'work.plan.updated',
        label: 'Work',
        detail: 'Work plan projected from existing run events',
        time: '10:25',
        status: 'running',
        metadata: {
          work_goal: 'Ship the M16 Work mode foundation thin slice',
          work_steps: [
            { id: 'm16-step-1', title: 'Reuse Thread.mode = work', status: 'completed', summary: 'Keep Work mode on existing thread and run surfaces.' },
            { id: 'm16-step-2', title: 'Project progress from events', status: 'running', summary: 'Use run events and messages as the source of truth.' },
            { id: 'm16-step-3', title: 'Render safe artifact references', status: 'pending', summary: 'Metadata preview only; no file execution.' },
          ],
          work_artifacts: [
            {
              id: 'm16-artifact-plan',
              title: 'M16 Work Plan',
              type: 'markdown',
              source_thread_id: 'thread-brief',
              source_run_id: 'run-1',
              summary: 'Safe markdown-like preview for the current Work mode plan.',
              created_at: '2026-05-25 10:25',
              updated_at: 'Now',
            },
          ],
        },
      },
      {
        id: 'evt-m22-todo',
        type: 'work.todo.updated',
        label: 'Todo',
        detail: 'Todo replayed from safe run metadata',
        time: '10:26',
        status: 'running',
        metadata: {
          todo_items: [
            { id: 'm22-todo-1', title: 'Find candidate files', status: 'completed' },
            { id: 'm22-todo-2', title: 'Read selected file', status: 'running', summary: 'Safe metadata only' },
          ],
          updated_by: 'runtime',
          redaction_applied: false,
        },
      },
      { id: 'evt-2', type: 'context.loaded', label: 'Context', detail: 'Docs and reference map', time: '10:25', status: 'completed' },
      { id: 'evt-m22-tool-1', type: 'tool.call.approval_required', label: 'Tool', detail: 'workspace.glob waiting for approval', time: '10:27', status: 'running', metadata: { tool_call_id: 'tc_glob_1', tool_name: 'workspace.glob', loop_index: 1, loop_max: 6, approval_status: 'required', execution_status: 'blocked' } },
      { id: 'evt-m22-tool-2', type: 'tool.call.succeeded', label: 'Tool', detail: 'workspace.glob completed', time: '10:28', status: 'completed', metadata: { tool_call_id: 'tc_glob_1', tool_name: 'workspace.glob', loop_index: 1, loop_max: 6, execution_status: 'succeeded' } },
      { id: 'evt-m22-continuation', type: 'model.request.started', label: 'Model', detail: 'Continuation after workspace.glob', time: '10:28', status: 'running', metadata: { model_phase: 'continuation' } },
      { id: 'evt-m22-tool-3', type: 'tool.call.approval_required', label: 'Tool', detail: 'workspace.read waiting for approval', time: '10:29', status: 'running', metadata: { tool_call_id: 'tc_read_2', tool_name: 'workspace.read', loop_index: 2, loop_max: 6, approval_status: 'required', execution_status: 'blocked' } },
      { id: 'evt-m23-tool-1', type: 'tool.call.approval_required', label: 'Tool', detail: 'workspace.write_file waiting for approval', time: '10:30', status: 'running', metadata: { tool_call_id: 'tc_write_3', tool_name: 'workspace.write_file', tool_group: 'workspace', loop_index: 3, loop_max: 6, approval_status: 'required', execution_status: 'blocked' } },
      { id: 'evt-m23-tool-2', type: 'tool.call.succeeded', label: 'Tool', detail: 'workspace.edit completed', time: '10:31', status: 'completed', metadata: { tool_call_id: 'tc_edit_4', tool_name: 'workspace.edit', tool_group: 'workspace', execution_status: 'succeeded', result_summary: { operation: 'edit', path: 'src/notes.txt', changed: true } } },
      { id: 'evt-m24-tool-1', type: 'tool.call.approval_required', label: 'Tool', detail: 'sandbox.exec_command waiting for approval', time: '10:32', status: 'running', metadata: { tool_call_id: 'tc_exec_5', tool_name: 'sandbox.exec_command', tool_group: 'sandbox', approval_status: 'required', execution_status: 'blocked', arguments_summary: { argv: ['pwd'], cwd: '.', timeout_ms: 5000 } } },
      { id: 'evt-m24-tool-2', type: 'tool.call.succeeded', label: 'Tool', detail: 'sandbox.exec_command completed', time: '10:33', status: 'completed', metadata: { tool_call_id: 'tc_exec_5', tool_name: 'sandbox.exec_command', tool_group: 'sandbox', execution_status: 'succeeded', result_summary: { operation: 'exec_command', cwd: '.', exit_code: 0, stdout_truncated: false, stderr_truncated: false } } },
      { id: 'evt-m25-tool-1', type: 'tool.call.approval_required', label: 'Tool', detail: 'lsp.symbols waiting for approval', time: '10:34', status: 'running', metadata: { tool_call_id: 'tc_lsp_6', tool_name: 'lsp.symbols', tool_group: 'lsp', approval_status: 'required', execution_status: 'blocked', arguments_summary: { path: 'src/main.go', query: 'Tool' } } },
      { id: 'evt-m25-tool-2', type: 'tool.call.succeeded', label: 'Tool', detail: 'lsp.symbols completed', time: '10:35', status: 'completed', metadata: { tool_call_id: 'tc_lsp_6', tool_name: 'lsp.symbols', tool_group: 'lsp', execution_status: 'succeeded', result_summary: { operation: 'symbols', path: 'src/main.go', count: 1 } } },
      { id: 'evt-m26-tool-1', type: 'tool.call.approved', label: 'Tool', detail: 'web.fetch auto-approved', time: '10:36', status: 'running', metadata: { tool_call_id: 'tc_web_7', tool_name: 'web.fetch', tool_group: 'web', approval_status: 'approved', execution_status: 'not_started', arguments_summary: { url: 'https://example.com/docs', max_bytes: 4096 } } },
      { id: 'evt-m26-tool-2', type: 'tool.call.succeeded', label: 'Tool', detail: 'web.fetch completed', time: '10:37', status: 'completed', metadata: { tool_call_id: 'tc_web_7', tool_name: 'web.fetch', tool_group: 'web', execution_status: 'succeeded', result_summary: { operation: 'fetch', status_code: 200, final_url: 'https://example.com/docs', truncated: false } } },
      { id: 'evt-m27-tool-1', type: 'tool.call.approval_required', label: 'Tool', detail: 'browser.open waiting for approval', time: '10:38', status: 'running', metadata: { tool_call_id: 'tc_browser_8', tool_name: 'browser.open', tool_group: 'browser', approval_status: 'required', execution_status: 'blocked', arguments_summary: { url: 'https://example.com/docs', max_bytes: 4096 } } },
      { id: 'evt-m27-tool-2', type: 'tool.call.succeeded', label: 'Tool', detail: 'browser.open completed', time: '10:39', status: 'completed', metadata: { tool_call_id: 'tc_browser_8', tool_name: 'browser.open', tool_group: 'browser', execution_status: 'succeeded', result_summary: { operation: 'open', session_id: 'br_mock', final_url: 'https://example.com/docs', title: 'Docs', link_count: 1 } } },
      { id: 'evt-m27-tool-3', type: 'tool.call.succeeded', label: 'Tool', detail: 'browser.snapshot completed', time: '10:40', status: 'completed', metadata: { tool_call_id: 'tc_browser_9', tool_name: 'browser.snapshot', tool_group: 'browser', execution_status: 'succeeded', result_summary: { operation: 'snapshot', session_id: 'br_mock', current_url: 'https://example.com/docs', title: 'Docs', text_excerpt: 'Safe bounded text' } } },
      { id: 'evt-m28-tool-1', type: 'tool.call.approval_required', label: 'Tool', detail: 'artifact.create_text waiting for approval', time: '10:41', status: 'running', metadata: { tool_call_id: 'tc_artifact_10', tool_name: 'artifact.create_text', tool_group: 'artifact', approval_status: 'required', execution_status: 'blocked', arguments_summary: { title: 'Notes' } } },
      { id: 'evt-m28-tool-2', type: 'tool.call.succeeded', label: 'Tool', detail: 'artifact.create_text completed', time: '10:42', status: 'completed', metadata: { tool_call_id: 'tc_artifact_10', tool_name: 'artifact.create_text', tool_group: 'artifact', execution_status: 'succeeded', result_summary: { operation: 'create_text', artifact_id: 'art_mock', title: 'Notes', content_bytes: 18, text_excerpt: 'Safe bounded text' } } },
      { id: 'evt-m28-tool-3', type: 'tool.call.succeeded', label: 'Tool', detail: 'artifact.read completed', time: '10:43', status: 'completed', metadata: { tool_call_id: 'tc_artifact_11', tool_name: 'artifact.read', tool_group: 'artifact', execution_status: 'succeeded', result_summary: { operation: 'read', artifact_id: 'art_mock', title: 'Notes', text_excerpt: 'Safe bounded text' } } },
      { id: 'evt-m29-tool-1', type: 'tool.call.approval_required', label: 'Tool', detail: 'agent.spawn waiting for approval', time: '10:44', status: 'running', metadata: { tool_call_id: 'tc_agent_12', tool_name: 'agent.spawn', tool_group: 'agent', approval_status: 'required', execution_status: 'blocked', arguments_summary: { role: 'reviewer', goal: 'Review implementation' } } },
      { id: 'evt-m29-tool-2', type: 'tool.call.succeeded', label: 'Tool', detail: 'agent.list completed', time: '10:45', status: 'completed', metadata: { tool_call_id: 'tc_agent_13', tool_name: 'agent.list', tool_group: 'agent', execution_status: 'succeeded', result_summary: { operation: 'list', count: 1, autonomous_execution: false } } },
      { id: 'evt-m29-tool-3', type: 'tool.call.succeeded', label: 'Tool', detail: 'agent.complete completed', time: '10:46', status: 'completed', metadata: { tool_call_id: 'tc_agent_14', tool_name: 'agent.complete', tool_group: 'agent', execution_status: 'succeeded', result_summary: { operation: 'complete', status: 'completed', result_summary: 'No safety issue found', autonomous_execution: false } } },
      { id: 'evt-3', type: 'tool.completed', label: 'Tool', detail: 'Reference scan complete', time: '10:26', status: 'completed' },
      { id: 'evt-4', type: 'message.drafting', label: 'Drafting', detail: 'Preparing UI shell', time: 'Now', status: 'running' },
    ],
  },
  {
    id: 'run-2',
    threadId: 'thread-docs',
    status: 'completed',
    model: 'Claude Sonnet',
    context: '18k / 128k',
    events: [
      { id: 'evt-5', type: 'run.started', label: 'Started', detail: 'Roadmap pass', time: '09:48', status: 'completed' },
      { id: 'evt-6', type: 'run.completed', label: 'Completed', detail: 'M1 boundary confirmed', time: '09:49', status: 'completed' },
    ],
  },
  {
    id: 'run-3',
    threadId: 'thread-agent',
    status: 'stopped',
    model: 'Claude Sonnet',
    context: '9k / 128k',
    events: [
      { id: 'evt-7', type: 'run.started', label: 'Started', detail: 'Agent profile sketch', time: 'Yesterday', status: 'completed' },
      { id: 'evt-8', type: 'run.stopped', label: 'Stopped', detail: 'Paused by user', time: 'Yesterday', status: 'stopped' },
    ],
  },
]
